import pygame

WINDOW_WIDTH, WINDOW_HEIGHT = 1600, 900
FRAMERATE = 72
## Player
PLAYER_SPEED = 400
PLAYER_ANIMATION_SPEED = 10
PLAYER_GRAVITY = 2400
PLAYER_TERMINAL_VELOCITY = 2000
PLAYER_JUMP_SPEED = 1000
PLAYER_DASH_SPEED = 800
PLAYER_DASH_TIME = 300
PLAYER_DASH_INVINCIBILITY = 125
PLAYER_WALL_JUMP_SPEED = 1000
PLAYER_WALL_SLIDE_SPEED = 200
PLAYER_BULLET_SPEED = 800
PLAYER_BULLET_DELAY = 200
PLAYER_MAX_HEALTH = 6
PLAYER_INVINCIBILITY_TIME = 1000
PLAYER_KNOCKBACK_SPEED = 500
PLAYER_KNOCKBACK_TIME = 500
PLAYER_DUCK_KEY = pygame.K_DOWN
PLAYER_LEFT_KEY = pygame.K_LEFT
PLAYER_RIGHT_KEY = pygame.K_RIGHT
PLAYER_JUMP_KEY = pygame.K_z
PLAYER_SHOOT_KEY = pygame.K_x
PLAYER_DASH_KEY = pygame.K_c
PLAYER_STRAFE_KEY = pygame.K_LSHIFT
PLAYER_RESTART_KEY = pygame.K_k
PLAYER_FRAMERATE_KEY = pygame.K_p
PLAYER_FULLSCREEN_KEY = pygame.K_f
## Enemy
ENEMY_ANIMATION_SPEED = 5
ENEMY_BULLET_SPEED = 400
ENEMY_BULLET_DELAY = 1000
ENEMY_TURN_DELAY_MIN = 1000
ENEMY_TURN_DELAY_MAX = 2000
ENEMY_AGGRO_DISTANCE = 750
ENEMY_MAX_HEALTH = 2
ENEMY_BLINK_TIME = 100
## Game Logic
BULLET_FADE_TIME = 5000
FIRE_ANIMATION_SPEED = 24
## Platforms
PLATFORM_SPEED = 200
## Sound
MUSIC_VOLUME, SOUND_VOLUME = 0.5, 0.25

LAYERS = {
	'bg': 0,
	'bg detail': 1,
	'main': 2,
	'fg detail bottom': 3,
	'fg detail top': 4,
}

PATHS = {
	'map': "data/map.tmx",
	'bg': "graphics/sky/bg_sky.png",
	'fg': "graphics/sky/fg_sky.png",
	'player': "graphics/player",
	'enemy': "graphics/enemies/standard",
	'bullet': "graphics/bullet.png",
	'fire': "graphics/fire"
}